###Created on February 21, 2022
###author: liujinxu

library(Seurat)
library(monocle)

library(argparse)
parser = ArgumentParser()
parser$add_argument("--seurat_path", help="Seurat filter  .rds ")
parser$add_argument("--outdir", help='output folder',required=TRUE,default="./")
parser$add_argument("--genelist",help='Gene,Gene_name.csv of high_varience_gene or cluster diff gene')
parser$add_argument("--cluster_label",help='cluster info of each barcode,generated by 10Xcellranger',required=TRUE)
parser$add_argument("--ordering_gene", help='Alternative choices for choosing genes that define a cell\'s progress,[differential,dispersion]',default="dispersion")
args <- parser$parse_args()
str(args)

seurat_path = args$seurat_path
outdir = args$outdir
cluster_label = args$cluster_label
genelist = args$genelis


if(is.null(seurat_path)){
gbm <- read10X(pipestance_path)
seurat_object = CreateSeuratObject(gbm)
}else{
seurat_object =  readRDS(seurat_path)
}

clus<-read.csv(cluster_label,header=TRUE)
clus$Cluster <- as.factor(clus$Cluster)
m<-intersect(clus$Barcode,colnames(seurat_object))
seurat_match<- subset(x = seurat_object ,cells= m)

data <- as(as.matrix(seurat_match@assays$RNA@counts),'sparseMatrix')
pd <- new('AnnotatedDataFrame', data = as.data.frame(seurat_match@meta.data))
fData <- data.frame(gene_short_name = row.names(data), row.names = row.names(data))
fd <- new('AnnotatedDataFrame', data = fData)

gbm_cds <- newCellDataSet(data,
                              phenoData = pd,
                              featureData = fd,
                              lowerDetectionLimit = 0.5,
                              expressionFamily = negbinomial.size())


pData(gbm_cds)$Barcode <-rownames(pData(gbm_cds))
new_pData<-merge(pData(gbm_cds),clus,by="Barcode",sort=F)
rownames(new_pData)<-rownames(pData(gbm_cds))
pData(gbm_cds)<-new_pData

gbm_cds <- estimateSizeFactors(gbm_cds)
gbm_cds <- estimateDispersions(gbm_cds)
disp_table <- dispersionTable(gbm_cds)

if (!is.null(genelist)){
  hvg <- read.table(genelist,header = T,sep=',',stringsAsFactors = F)
  gbm_cds <- setOrderingFilter(gbm_cds, hvg$Gene)
}else if(!is.null(seurat_path)){
        seurat_match <- FindVariableFeatures(seurat_match)
        gbm_cds <- setOrderingFilter(gbm_cds,seurat_match@assays$RNA@var.features)
}else {ordering_genes <- subset(disp_table,mean_expression >= 0.1 &dispersion_empirical >= 1 * dispersion_fit) 
gbm_cds <- setOrderingFilter(gbm_cds, ordering_genes$gene_id)
}
gbm_cds <- reduceDimension(gbm_cds, max_components = 2,reduction_method = 'DDRTree')
gbm_cds <- orderCells(gbm_cds)  
saveRDS(gbm_cds,file=paste0(outdir,'/','monocle.rds'))

